//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace praktikaAnohin.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class id_
    {
        public int id { get; set; }
        public Nullable<int> id_vladelca { get; set; }
        public Nullable<int> id_avto { get; set; }
        public Nullable<int> id_storozha { get; set; }
        public Nullable<int> id_zapisi { get; set; }
    
        public virtual Ohrana Ohrana { get; set; }
        public virtual Prihod___uhod_avto Prihod___uhod_avto { get; set; }
        public virtual Spiski_vladelca Spiski_vladelca { get; set; }
        public virtual Spisok_Avto Spisok_Avto { get; set; }
    }
}
