//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace praktikaAnohin.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spisok_Avto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Spisok_Avto()
        {
            this.id_ = new HashSet<id_>();
        }
    
        public int Id_avto { get; set; }
        public string marka_avto { get; set; }
        public string model_avto { get; set; }
        public string gos_znak { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<id_> id_ { get; set; }
    }
}
